import { Box, Button, Group, Tabs, TextInput } from "@mantine/core";
import { useForm } from "@mantine/form";
import { showNotification } from "@mantine/notifications";
import { Inter } from "@next/font/google";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });
type User = {
  username: string;
  password: string;
};
export default function Home() {
  const form = useForm({
    initialValues: {
      username: "",
      password: "",
    },
    validate: {
      username: (value) =>
        /^[a-zA-Z0-9]{3,30}$/.test(value) ? null : "Invalid username.",
      password: (value) =>
        /^(?=.*\d)(?=.*[!@#$%^&*])(?=.*[a-z])(?=.*[A-Z]).{8,}$/.test(value)
          ? null
          : "Invalid password.",
    },
  });

  const login = async (data: User) => {
    const resp = await fetch("http://localhost:9000/auth/login", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify(data),
    });
    if (!resp.ok) {
      const error = await resp.json();
      showNotification({
        title: "Error",
        message: error.message,
        color: "red",
      });
      return;
    }
    const token = await resp.json();
    window.localStorage.setItem("access_token", token.access_token);
  };
  return (
    <>
      <Head>
        <title>Next TODO</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box
        sx={{
          display: "flex",
          justifyContent: "center",
          height: "100vh",
          alignItems: "center",
        }}
      >
        <Box sx={{ width: "50%" }}>
          <Tabs defaultValue="login">
            <Tabs.List>
              <Tabs.Tab value="login">Log In</Tabs.Tab>
              <Tabs.Tab value="signup">Sign Up</Tabs.Tab>
            </Tabs.List>
            <Tabs.Panel value="login">
              <Box>
                <h1>Log In</h1>
                <form onSubmit={form.onSubmit(login)}>
                  <TextInput
                    withAsterisk
                    label="Username"
                    placeholder="Username"
                    {...form.getInputProps("username")}
                  />
                  <TextInput
                    withAsterisk
                    label="Password"
                    placeholder="Password"
                    type="password"
                    {...form.getInputProps("password")}
                  />
                  <Group position="right" mt="md">
                    <Button type="submit">Submit</Button>
                  </Group>
                </form>
              </Box>
            </Tabs.Panel>
            <Tabs.Panel value="signup">
              <Box>
                <h1>Sign Up</h1>
                <form onSubmit={form.onSubmit(login)}>
                  <TextInput
                    disabled
                    withAsterisk
                    label="Username"
                    placeholder="Username"
                    {...form.getInputProps("username")}
                  />
                  <TextInput
                    disabled
                    withAsterisk
                    label="Password"
                    placeholder="Password"
                    type="password"
                    {...form.getInputProps("password")}
                  />
                  <Group position="right" mt="md">
                    <Button disabled type="submit">
                      Submit
                    </Button>
                  </Group>
                </form>
              </Box>
            </Tabs.Panel>
          </Tabs>
        </Box>
      </Box>
    </>
  );
}
